FROM python:3.12-slim

WORKDIR /app

# Install system dependencies (optional, for watchdog)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-dev.txt ./
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY src/ ./

EXPOSE 8080

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=8080", "--debug"]