services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/app:/app
      - /home/jporcenaluk/keys/marino-emissions-app-ddd3dd1803cb.json:/keys/marino-emissions-app.json
    ports:
      - '8080:8080'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - STATIC_FOLDER=../frontend/build
      - GOOGLE_APPLICATION_CREDENTIALS=/keys/marino-emissions-app.json
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend